# Generated by Django 2.1.7 on 2019-03-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0010_auto_20190317_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_nasc_usuario',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
