# Generated by Django 2.1.7 on 2019-03-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0011_auto_20190318_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelace.Usuario')),
            ],
            options={
                'verbose_name_plural': 'PerfilUsuario',
            },
        ),
    ]
