# Generated by Django 2.1.7 on 2019-03-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0015_formulario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
