# Generated by Django 2.1.7 on 2019-03-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0016_delete_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='nota_estabelecimento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
    ]
