# Generated by Django 2.1.7 on 2019-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0017_auto_20190319_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nota_estabelecimento',
            field=models.CharField(default='', max_length=10),
        ),
    ]
